version: '3'
services:
    web:
        image: nginx:1.15-alpine
        ports:
            - "80:80"
        links:
            - app
            - loginsrv
        volumes:
            - ./web/default.conf:/etc/nginx/conf.d/default.conf

    loginsrv:
        image: tarent/loginsrv
        env_file: .env

    app:
        build: ./app
        env_file: .env
